DELETE http://localhost:8080/posts/3
Content-Type: application/json


###
GET http://localhost:8080/posts/post?since=1698711649507
Accept: application/json

###
GET http://localhost:8080/posts/3
Accept: application/json

###
POST http://localhost:8080/posts/
Content-Type: application/json

{
  "text": "Lab6 is so funny!"
}

###
POST http://localhost:8080/posts/
Content-Type: application/json

{
  "text": "MSD is a good program"
}


###
POST http://localhost:8080/posts/
Content-Type: application/json

{
  "text": "I like kotlin!"
}

###
POST http://localhost:8080/posts/
Content-Type: application/json

{
  "text": "I dont like kotlin!"
}

###

GET http://localhost:8080/posts
Accept: application/json


